version: '3'
services:
  # node-api:
  #   container_name: node-api
  #   build: '.'
  #   restart: always
  #   volumes:
  #     - .:/home/node/api
  #     - /home/node/api/node_modules
  #   networks:
  #     - app-net
  #   ports:
  #     - '3000:3000'
    # depends_on:
    #   - postgres-api
    #   - sonic-api

  # postgres-api:
  #   container_name: postgres-api
  #   image: postgres:13
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: moviemoji
  #   networks:
  #     - app-net

  sonic-api:
    container_name: sonic-api
    image: valeriansaliou/sonic:v1.3.0
    restart: unless-stopped
    ports:
      - 1491:1491
    volumes:
      - ./sonic/config.cfg:/etc/sonic.cfg
      - ./sonic/store/:/var/lib/sonic/store/
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
